// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLIAfHnSTp5MoNdf4P81vQzDTFe-Ho8M',
    appId: '1:958870929483:web:da87cdc4cf1c8745e20dce',
    messagingSenderId: '958870929483',
    projectId: 'foodsaver-6691f',
    authDomain: 'foodsaver-6691f.firebaseapp.com',
    storageBucket: 'foodsaver-6691f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOD5k_Jyabx3vlhZ94zKURbSZuWqS2_A',
    appId: '1:958870929483:android:b7df6267a1eb678de20dce',
    messagingSenderId: '958870929483',
    projectId: 'foodsaver-6691f',
    storageBucket: 'foodsaver-6691f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr8Tcxtn5MqClaVjzfi7NrvswDwkoC08U',
    appId: '1:958870929483:ios:606f40a721545ed5e20dce',
    messagingSenderId: '958870929483',
    projectId: 'foodsaver-6691f',
    storageBucket: 'foodsaver-6691f.appspot.com',
    iosBundleId: 'com.example.foodsaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr8Tcxtn5MqClaVjzfi7NrvswDwkoC08U',
    appId: '1:958870929483:ios:dcf8c1864cc1440de20dce',
    messagingSenderId: '958870929483',
    projectId: 'foodsaver-6691f',
    storageBucket: 'foodsaver-6691f.appspot.com',
    iosBundleId: 'com.example.foodsaver.RunnerTests',
  );
}
